#!/bin/bash
#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
#
# Reset the iptables to open the firewall ports on the local VM
# Access to ports is controlled from OCI Security rules
# Added
/opt/scripts/reset_iptables.sh

fileName=$(basename $BASH_SOURCE)


logs_dir=$(curl -H "Authorization: Bearer Oracle" -L http://169.254.169.254/opc/v2/instance/metadata/logs_dir)
mkdir -p ${logs_dir}
log_file="${logs_dir}/bootstrap.log"

function log() {
    while IFS= read -r line; do
        DATE=`date '+%Y-%m-%d %H:%M:%S.%N'`
        echo "<$DATE>  $line"
    done
}

# Pre-create provisioning log as oracle user so it is owned by oracle user.
# This is to avoid race-condition if logging happens from a script running as root user first then
# provisioning log is created and owned by root user. So we pre-create it before any logging happens
# to provisioning log file.
sudo su - oracle -c "touch ${logs_dir}/provisioning.log"

# Call bootstrap.py to wait for provisioning marker
# This file is already part of the image.

python /opt/scripts/bootstrap.py | log >> $log_file

# Bootstrap.py unpacks the scripts to /opt/scripts directory.
# Ensure they are owned by oracle user and the shell scripts have execute file permission.

sudo chown -R oracle:oracle /u01
sudo chmod -R 775 /u01/
sudo chown -R oracle:oracle /opt
sudo chmod -R 775 /opt/
sudo chmod +x /opt/scripts/*.sh


# Append to oracle home bashrc so DOMAIN_HOME is configured for oracle user - this is required for migration
WLS_DOMAIN_NAME=$(sudo su oracle -c 'python /opt/scripts/databag.py wls_domain_name')
WLS_DOMAIN_DIR=$(sudo su oracle -c 'python /opt/scripts/databag.py domain_dir')
DOMAIN_HOME=$WLS_DOMAIN_DIR"/"$WLS_DOMAIN_NAME

echo "export DOMAIN_HOME=${DOMAIN_HOME}" >> /home/oracle/.bashrc

python /opt/scripts/mountVolume.py | log >> $log_file
exit_code=$?
if [ $exit_code -ne 0 ]; then
    echo "Error executing volume mounting.. Exiting provisioning" | log >> $log_file
    #clean up script
    /opt/scripts/tidyup.sh
    exit 1
fi

uuid=`sudo lsblk -no UUID $(df -P /u01/data/lost+found | awk 'END{print $1}')`
sudo sed -i -e "\$aUUID=${uuid} /u01/data ext4 auto,defaults,_netdev,nofail 0 2" /etc/fstab
 
if [ $? -eq 0 ]; then
  echo "Added entry for /u01/data in /etc/fstab" | log >> $log_file
else
  echo "Failed to add /etc/fstab entry. Exiting" | log >> $log_file
  #clean up script
  /opt/scripts/tidyup.sh
  exit 1
fi
 
sudo chmod +x /etc/rc.d/rc.local
sudo echo "sudo su - oracle -c /opt/scripts/restart/restart_12c_servers.sh > /u01/logs/reboot_servers.log" >> /etc/rc.d/rc.local
 
if [ $? -eq 0 ]; then
  echo "Added entry for SOA Server restart in /etc/rc.d/rc.local" | log >> $log_file
else
  echo "Failed to add /etc/rc.d/rc.local entry. Exiting" | log >> $log_file
  #clean up script
  /opt/scripts/tidyup.sh
  exit 1
fi

# Continue with initialization and append to the provisioning log both stdout and stderr

#check versions in prod version
echo "Executing check_versions script" | log >> $log_file

/opt/scripts/check_versions.sh
exit_code=$?

echo "Executed check_versions script with exit code [$exit_code]" | log >> $log_file

if [ $exit_code -eq 0 ]; then
    config_script="/opt/scripts/idcs/configure_test_idcs.sh"
    [[ -x ${config_script} ]] && ${config_script}
    rm -f ${config_script}

    echo "Executing terraform_init_idcs.sh" | log >> $log_file
    #Save stdout and stderr in variable and print it in case exit code is not zero
    terraform_init_log=$(su - oracle -c /opt/scripts/idcs/terraform_init_idcs.sh 2>&1)
    exit_code=$?
    echo "Executed terraform_init_idcs.sh with exit code [$exit_code]" | log >> $log_file
    [[ $exit_code -ne 0 ]] && echo "$terraform_init_log" | log >> $log_file
fi

if [ $exit_code -eq 0 ]; then
    echo "Executing install_cloudgate.sh" | log >> $log_file
    #Save stdout and stderr in variable and print it in case exit code is not zero
    install_clougate_log=$(/opt/scripts/idcs/install_cloudgate.sh 2>&1)
    exit_code=$?
    echo "Executed install_cloudgate.sh with exit code [$exit_code]" | log >> $log_file
    [[ $exit_code -ne 0 ]] && echo "$install_clougate_log" | log >> $log_file
fi


if [ $exit_code -eq 0 ]; then
    echo "Executing terraform_init.sh" | log >> $log_file
    su - oracle -c /opt/scripts/terraform_init.sh
    exit_code=$?
    echo "Executed terraform_init.sh with exit code [$exit_code]" | log >> $log_file
fi

echo "Executing cleanup script" | log >> $log_file

#clean up script
/opt/scripts/tidyup.sh

echo "Executed cleanup script" | log >> $log_file
